import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import { AuthProvider } from "./context/authContext";
import ProtectedRoute from "./protectedRoute";
import { Toaster } from "react-hot-toast";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans bg-background text-foreground`}
      >
        <Providers>
          <AuthProvider>
            <ProtectedRoute>
              <Navbar />
              {children}
              <Toaster position="top-right" reverseOrder={false} />
              <Footer />
              <Script
                src="//code.tidio.co/cszgdtdehvhfejvilapy3bzzpq6fvdno.js"
                async
              />
            </ProtectedRoute>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
